"""Safety guard: dashboard route list is frozen — no routes added or removed without review."""

from __future__ import annotations

import pytest

FROZEN_ROUTES: set[tuple[str, str]] = {
    # HTML pages
    ("GET", "/"),
    ("GET", "/sessions/{session_id}"),
    ("GET", "/traces"),
    ("GET", "/traces/{index}"),
    ("GET", "/integrity"),
    ("GET", "/settings"),
    ("GET", "/enterprise/settings"),
    # JSON API
    ("GET", "/api/stats"),
    ("GET", "/api/sessions"),
    ("GET", "/api/sessions/{session_id}/export"),
    ("POST", "/api/integrity/verify"),
    ("GET", "/api/settings"),
    # Runtime
    ("GET", "/runtime/capabilities"),
    # OpenAPI (auto-generated by FastAPI)
    ("GET", "/openapi.json"),
}


class TestDashboardRouteFreeze:
    """Dashboard routes must not change without explicit test update."""

    def test_all_frozen_routes_exist(self) -> None:
        """Every frozen route must exist in the app."""
        pytest.importorskip("fastapi")
        from atlasbridge.dashboard.app import create_app

        app = create_app()
        actual = set()
        for route in app.routes:
            if hasattr(route, "methods") and hasattr(route, "path"):
                for method in route.methods:
                    if method in ("GET", "POST", "PUT", "DELETE", "PATCH"):
                        actual.add((method, route.path))

        missing = FROZEN_ROUTES - actual
        assert not missing, f"Frozen routes missing from app: {missing}"

    def test_no_unexpected_routes(self) -> None:
        """No routes may be added without updating the frozen set."""
        pytest.importorskip("fastapi")
        from atlasbridge.dashboard.app import create_app

        app = create_app()
        actual = set()
        for route in app.routes:
            if hasattr(route, "methods") and hasattr(route, "path"):
                for method in route.methods:
                    if method in ("GET", "POST", "PUT", "DELETE", "PATCH"):
                        actual.add((method, route.path))

        unexpected = actual - FROZEN_ROUTES
        assert not unexpected, (
            f"Unexpected routes found (update FROZEN_ROUTES if intentional): {unexpected}"
        )

    def test_route_count_matches(self) -> None:
        """Route count must match frozen count exactly."""
        pytest.importorskip("fastapi")
        from atlasbridge.dashboard.app import create_app

        app = create_app()
        actual_count = 0
        for route in app.routes:
            if hasattr(route, "methods") and hasattr(route, "path"):
                for method in route.methods:
                    if method in ("GET", "POST", "PUT", "DELETE", "PATCH"):
                        actual_count += 1

        assert actual_count == len(FROZEN_ROUTES), (
            f"Route count drift: expected {len(FROZEN_ROUTES)}, got {actual_count}"
        )
